### ISSUE TITLE
Is this the expected output of the example?

### ISSUE THREAD

**Issue by jpuritz** [RAWWiberg/poolFreqDiff#2]
`python2 ./poolFreqDiffTest_QBGLM.py -filename test.sync -npops 4 -nlevels 2 -n 40 -mincnt 2 -minc 10 -maxc 100 -rescale nr -zeroes 1 > test.rin`

`Rscript test.rin > test.rout`

`cat test.rout`

```
# Loaded: poolFreqDiffTest.R
# Looking in:  /home/jpuritz/CASE/analysis/ALL_2/poolFreqDiff  for G_test.R
# Loaded: G_test.R
2       92271   C       0:0:28:16:0:0   0:0:36:13:0:0   0:0:26:18:0:0   0:0:28:17:0:0   0:0:24:13:0:0   0:0:25:17:0:0   0:0:38:14:0:0   0:0:29:17:0:0   0.877555554381598
2       92276   T       0:29:0:15:0:0   0:33:0:0:0:0    0:27:0:10:0:0   0:31:0:17:0:0   0:23:0:14:0:0   0:26:0:1:0:0    0:39:0:16:0:0   0:30:0:0:0:0    0.146127878475483
```

**Comment by RAWWiberg** [comment]
Yes, in the test data there are only two SNPs that pass the filtering criteria. And for neither SNP is there an association between the treatment line and the allele frequency. You can compare the output in the `test.rin` file to the input in the `test.sync`.

**Comment by jpuritz** [comment]
Ok.  This is confusing because of this [line](https://github.com/RAWWiberg/poolFreqDiff/blob/master/README.md?plain=1#L41) in the README

"one of which (line 7 [2:92276]) has a highly significant allele frequency difference between two treatments"

**Comment by RAWWiberg** [comment]
Yes, you're right. This was an oversight. I had planned to include a highly significant difference, but the way I made up the input data it turns out it isn't significant. I will update the README. Apologies for the confusion.

**Comment by jpuritz** [comment]
Thanks!

Jon Puritz, PhD (he/him)

Associate Professor
Department of Biological Sciences
University of Rhode Island
120 Flagg Road, Kingston, RI 02881


Webpage: MarineEvoEco.com

Cell:    401-338-8739
Work:  401-874-9020

"The most valuable of all talents is that of never using two words when one
will do.” -Thomas Jefferson
--------------------------------------------
*The University of Rhode Island occupies the traditional stomping ground of
the Narragansett Nation and the Niantic People. *

**Comment by RAWWiberg** [comment]
Just to follow up on this. I have modified the data in the `test.sync` file so that the SNP now has a significant difference in allele frequencies. My apologies for the earlier mistake, and thanks for catching this and reaching out!
