### ISSUE TITLE
New version throws error when rescaling

### ISSUE THREAD

**Issue by jpuritz** [RAWWiberg/poolFreqDiff#4]
`python ./poolFreqDiffTest_QBGLM.py -filename test.sync -npops 4 -nlevels 2 -n 40 -mincnt 2 -minc 10 -maxc 100 -rescale neff -zeroes 1 > test.rin`

```
Traceback (most recent call last):
  File "/poolFreqDiff/./poolFreqDiffTest_QBGLM.py", line 283, in <module>
    printRlines(SNP,major_alleles,npops,nlevels,n,mincnt,\
  File "/poolFreqDiff/./poolFreqDiffTest_QBGLM.py", line 141, in printRlines
    exec("sample_%s=pop[sam]") %(sam)
  File "<string>", line 1
    sample_%s=pop[sam]
    ^^^^^^^^^
SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='?
```

This happens with either rescaling option.

**Comment by RAWWiberg** [comment]
Hi, apologies for the delay, this was due to some bugs from my fix to make the code compatible with python3. I've fixed these bugs now and the new version should work. Let me know if there are still problems.
